#:schema node_modules/wrangler/config-schema.json
name = "sublink-workers"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "5ea673abc4d945eba3671febf4dc5657" }
]

[assets]
directory = "./public"
